In [68]:
import pandas as pd
import numpy as np

In [69]:
df_2020= pd.read_excel('2020.xlsx')
df_2021= pd.read_excel('2021.xlsx')
df_2022= pd.read_excel('2022.xlsx')

In [70]:
df_2020.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Nombre', 'Código NIF', 'Localidad',
       'Provincia', 'País', 'Código primario CNAE 2009',
       'Literal código CNAE 2009 primario', 'Fecha constitución',
       'Importador / Exportador', 'Países importación', 'Países exportación',
       'Otros activos líquidos\nmil EUR\n2020', 'Inmovilizado\nmil EUR\n2020',
       'Inmovilizado inmaterial\nmil EUR\n2020',
       'Inmovilizado material\nmil EUR\n2020',
       'Otros activos fijos\nmil EUR\n2020',
       'Activo circulante\nmil EUR\n2020', 'Existencias\nmil EUR\n2020',
       'Deudores\nmil EUR\n2020', 'Tesorería\nmil EUR\n2020',
       'Total activo\nmil EUR\n2020', 'Capital suscrito\nmil EUR\n2020',
       'Otros fondos propios\nmil EUR\n2020', 'Pasivo fijo\nmil EUR\n2020',
       'Acreedores a L. P.\nmil EUR\n2020',
       'Otros pasivos fijos\nmil EUR\n2020', 'Pasivo líquido\nmil EUR\n2020',
       'Deudas financieras\nmil EUR\n2020',
       'Acreedores comerciales\nmil EUR\n2020',
       'Otros pasivos líquidos\nmil EUR\n2020',
       'Total pasivo y capital propio\nmil EUR\n2020',
       'Número empleados\n2020', 'Ingresos de explotación\nmil EUR\n2020',
       'Importe neto Cifra de Ventas\nmil EUR\n2020',
       'Consumo de mercaderías y de materias\nmil EUR\n2020',
       'Resultado bruto\nmil EUR\n2020',
       'Otros gastos de explotación\nmil EUR\n2020',
       'Resultado Explotación\nmil EUR\n2020',
       'Ingresos financieros\nmil EUR\n2020',
       'Gastos financieros\nmil EUR\n2020',
       'Resultado financiero\nmil EUR\n2020',
       'Result. ordinarios antes Impuestos\nmil EUR\n2020',
       'Impuestos sobre sociedades\nmil EUR\n2020',
       'Resultado Actividades Ordinarias\nmil EUR\n2020',
       'Ingresos extraordinarios\nmil EUR\n2020',
       'Gastos extraordinarios\nmil EUR\n2020',
       'Resultados actividades extraordinarias\nmil EUR\n2020',
       'Resultado del Ejercicio\nmil EUR\n2020', 'Materiales\nmil EUR\n2020',
       'Gastos de personal\nmil EUR\n2020',
       'Dotaciones para amortiz. de inmovil.\nmil EUR\n2020',
       'Otros Conceptos de Explotación\nmil EUR\n2020',
       'Gastos financieros y gastos asimilados\nmil EUR\n2020'],
      dtype='object')

In [146]:
df_2020_ingexp = df_2020[['Código NIF','Ingresos de explotación\nmil EUR\n2020']]
df_2020_ingexp.replace('n.d.',np.nan,inplace=True)
df_2020_ingexp.isna().sum()

C:\Users\josu1\AppData\Local\Temp\ipykernel_4112\2950529900.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020_ingexp.replace('n.d.',np.nan,inplace=True)

Código NIF                                   0
Ingresos de explotación\nmil EUR\n2020    7574
dtype: int64

In [133]:
df_2022_col=df_2022[['Nombre', 'Código NIF', 'Localidad',
       'Provincia', 'País', 'Código primario CNAE 2009',
       'Literal código CNAE 2009 primario', 'Fecha constitución',
       'Importador / Exportador', 'Países importación', 'Países exportación','Resultado del Ejercicio\nmil EUR\n2022',
       'Total activo\nmil EUR\n2022', 'Ingresos de explotación\nmil EUR\n2022', 'Activo circulante\nmil EUR\n2022', 
       'Pasivo líquido\nmil EUR\n2022', 'Resultado Explotación\nmil EUR\n2022',  
       'Otros activos líquidos\nmil EUR\n2022','Capital suscrito\nmil EUR\n2022',
       'Otros fondos propios\nmil EUR\n2022',]]
df_2022_col.head()

,Nombre,Código NIF,Localidad,Provincia,País,Código primario CNAE 2009,Literal código CNAE 2009 primario,Fecha constitución,Importador / Exportador,Países importación,Países exportación,Resultado del Ejercicio\nmil EUR\n2022,Total activo\nmil EUR\n2022,Ingresos de explotación\nmil EUR\n2022,Activo circulante\nmil EUR\n2022,Pasivo líquido\nmil EUR\n2022,Resultado Explotación\nmil EUR\n2022,Otros activos líquidos\nmil EUR\n2022,Capital suscrito\nmil EUR\n2022,Otros fondos propios\nmil EUR\n2022
0,IBERDROLA CLIENTES SOCIEDAD ANONIMA.,A95758389,BILBAO,Vizcaya,ESPANA,3514,Comercio de energía eléctrica,2014-03-17 00:00:00,Exportador,NaN,UE,627609,3252348,14505887,2768672,1678552,808712,439508,155295,1344809
1,PAN AMERICAN ENERGY SL.,B88260203,BILBAO,Vizcaya,ESPANA,6420,Actividades de las sociedades holding,1997-09-29 00:00:00,Exportador,NaN,ARGENTINA,477940,14448655,5112628,1700432,1727270,578995,742038,2093033,5777889
2,IBERDROLA ENERGIA ESPAÑA SOCIEDAD ANONIMA.,A95758371,BILBAO,Vizcaya,ESPANA,4611,Intermediarios del comercio de materias primas...,2014-03-17 00:00:00,Exportador,NaN,UE,923275,7184141,5004915,3882794,2219290,1564280,2676848,1985452,-772285
3,ALVEAN SUGAR SOCIEDAD LIMITADA.,B95773057,BILBAO,Vizcaya,ESPANA,4636,"Comercio al por mayor de azúcar, chocolate y c...",2014-07-17 00:00:00,Importador / Exportador,NaN,NaN,67407,835248,3994744,799119,487710,84885,352001,30857,312183
4,"IBERDROLA, SOCIEDAD ANONIMA",A48010615,BILBAO,Vizcaya,ESPANA,6420,Actividades de las sociedades holding,1901-07-19 00:00:00,Exportador,NaN,UE,2840000,53343000,3058000,3301000,10228000,3167000,3003000,4772000,26909000

Descartamos el df del 2021 al ver una gran cantidad de duplicados y al tener muchos menos datos no repetidos que el resto de los df.

In [134]:
nif_comunes =  set(df_2020['Código NIF'])&set(df_2022['Código NIF'])
len(nif_comunes)

39464

In [135]:
paises=list(df_2022_col[['Países exportación']].value_counts().index)
paises

[('UE',),
 ('EUROPA',),
 ('FRANCIA',),
 ('PORTUGAL',),
 ('UE;EEUU',),
 ('MEXICO',),
 ('FRANCIA;PORTUGAL',),
 ('AMERICA;ASIA;EUROPA',),
 ('CENTRO AMERICA;SUDAMERICA;UE',),
 ('SUDAMERICA;UE',),
 ('ALEMANIA;FRANCIA',),
 ('CUBA',),
 ('ALEMANIA',),
 ('EEUU',),
 ('AMERICA;UE',),
 ('ITALIA',),
 ('AFRICA;AMERICA;ASIA;EUROPA;OCEANIA',),
 ('AFRICA;AMERICA;ASIA;EUROPA',),
 ('CHINA',),
 ('AMERICA',),
 ('SUECIA',),
 ('ALEMANIA;FRANCIA;ITALIA;PORTUGAL',),
 ('CENTRO AMERICA;SUDAMERICA',),
 ('AMERICA;EUROPA',),
 ('ALEMANIA;EEUU;UK',),
 ('BELGICA',),
 ('EUROPA;CENTRO AMERICA;SUDAMERICA',),
 ('EUROPA;SUDAMERICA',),
 ('EUROPA;EEUU',),
 ('UE;AMERICA',),
 ('INDIA',),
 ('INDIA;FRANCIA;CHINA',),
 ('INDIA;PORTUGAL',),
 ('EUROPA;AUSTRALIA;CANADA;EEUU;JAPON;NUEVA ZELANDA',),
 ('INDIA;SUECIA',),
 ('IRLANDA;EEUU;AUSTRALIA;FRANCIA;CANADA',),
 ('EUROPA;ALEMANIA;SUECIA;FRANCIA;UK',),
 ('EUROPA;BRASIL;SUDAFRICA',),
 ('ITALIA;FRANCIA',),
 ('ITALIA;FRANCIA;JAPON;ALEMANIA;AUSTRIA;EEUU;UK;ARABIA SAUDI',),
 ('ITALIA;POLONIA;UK;SUDAFRICA',),
 ('ITALIA;PORTUGAL',),
 ('KAZAJSTAN',),
 ('MARRUECOS',),
 ('FRANCIA;UK;RUMANIA',),
 ('FRANCIA;ITALIA;PAISES BAJOS;UK;ALEMANIA;POLONIA;COLOMBIA;BRASIL;MEXICO;MALI;SUECIA;COSTA DE MARFIL',),
 ('FRANCIA;UK',),
 ('FRANCIA;ITALIA;PORTUGAL;UK',),
 ('FRANCIA;SUDAMERICA',),
 ('EUROPA;EEUU;MEXICO',),
 ('EUROPA;EEUU;RUSIA;TAIWAN',),
 ('EUROPA;NORTE AMERICA;SUDAMERICA;ARGENTINA;COLOMBIA;EEUU;MEXICO',),
 ('FRANCIA;PORTUGAL;UK;BELGICA;DINAMARCA;ALEMANIA;PAISES BAJOS',),
 ('EUROPA;ORIENTE MEDIO;CHINA;EGIPTO',),
 ('EUROPA;UK',),
 ('FRANCIA;PORTUGAL;ITALIA',),
 ('FRANCIA;ALEMANIA',),
 ('FRANCIA;ALEMANIA;SUIZA;AUSTRIA;BELGICA',),
 ('FRANCIA;BELGICA;PORTUGAL',),
 ('FRANCIA;EUROPA',),
 ('FRANCIA;ITALIA',),
 ('FRANCIA;MARRUECOS;SENEGAL',),
 ('AFRICA',),
 ('MEXICO;ALEMANIA;EEUU;CHINA',),
 ('MEXICO;CUBA;ITALIA;FRANCIA',),
 ('UE;ALEMANIA;BELGICA;FRANCIA',),
 ('UE;ALEMANIA;EEUU;UK;SUIZA',),
 ('UE;AMERICA;ARABIA SAUDI',),
 ('UE;ANDORRA',),
 ('UE;AUSTRALIA;INDONESIA;MALASIA',),
 ('UE;CANADA;EEUU;UK',),
 ('UE;CHINA;EEUU',),
 ('UE;CHINA;HONG KONG',),
 ('UE;CHINA;MEXICO',),
 ('UE;IRAN',),
 ('UE;JAPON',),
 ('UE;MARRUECOS',),
 ('UE;PORTUGAL',),
 ('UE;SUECIA',),
 ('UE;UK',),
 ('UE;UK;TURQUIA',),
 ('UK',),
 ('UK;ALEMANIA;BELGICA;EEUU;IRLANDA;FRANCIA;ITALIA;EUROPA;JAPON',),
 ('UK;FRANCIA;ALEMANIA;EEUU;RUSIA;POLONIA',),
 ('UE;ALEMANIA;AUSTRALIA;EEUU;FRANCIA;INDIA;JAPON',),
 ('UE;AFRICA',),
 ('TURQUIA;ESLOVENIA;MEXICO;EEUU;CANADA;INDONESIA;AUSTRALIA;INDIA;COREA DEL SUR;CHINA',),
 ('PORTUGAL;MARRUECOS;TUNEZ;SUDAFRICA;ANGOLA;MOZAMBIQUE',),
 ('MEXICO;ECUADOR;COLOMBIA;POLONIA;ESLOVENIA;LIBIA;INDIA;QATAR;ARABIA SAUDI',),
 ('MEXICO;POLONIA',),
 ('MEXICO;PORTUGAL;RUMANIA',),
 ('NIGERIA;FILIPINAS',),
 ('ORIENTE MEDIO;UCRANIA;RUSIA',),
 ('EUROPA;ALEMANIA;BELGICA;CHINA;JAPON',),
 ('PAKISTAN',),
 ('PORTUGAL;CHILE',),
 ('PORTUGAL;SUDAMERICA',),
 ('TUNEZ;PORTUGAL;SUECIA;ALEMANIA;IRLANDA;BELGICA;FRANCIA;PAISES BAJOS;UK',),
 ('REPUBLICA CHECA;UK;MEXICO',),
 ('REPUBLICA DOMINICANA',),
 ('RUMANIA',),
 ('SERBIA;POLONIA;MEXICO;BRASIL;ALEMANIA;ISRAEL;INDIA;PORTUGAL;RUSIA;SUECIA',),
 ('SUDAMERICA',),
 ('SUDAMERICA;EEUU',),
 ('SUECIA;NORUEGA;ALEMANIA;EEUU;FRANCIA;UK;PAISES BAJOS',),
 ('SUIZA;FRANCIA;ALEMANIA',),
 ('PAISES BAJOS;FRANCIA;ITALIA;UK;ALEMANIA',),
 ('EEUU;ASIA;EUROPA;CENTRO AMERICA',),
 ('ESLOVAQUIA;MEXICO',),
 ('ARGENTINA;URUGUAY',),
 ('ALEMANIA;CHINA;COREA DEL SUR;ESLOVAQUIA;EEUU;FRANCIA;HUNGRIA;INDIA;ITALIA;JAPON;MEXICO;POLONIA;PORTUGAL;RUSIA',),
 ('ALEMANIA;DINAMARCA;FRANCIA;PAISES BAJOS;UK;SUIZA',),
 ('ALEMANIA;EEUU;FRANCIA',),
 ('ALEMANIA;ESLOVAQUIA;FRANCIA;REPUBLICA CHECA',),
 ('ALEMANIA;FRANCIA;ARGENTINA;PAISES BAJOS;MEXICO;BELGICA',),
 ('ALEMANIA;FRANCIA;ISRAEL;ITALIA;POLONIA',),
 ('ALEMANIA;FRANCIA;UK;PAISES BAJOS;PORTUGAL;SUIZA',),
 ('ALEMANIA;INDONESIA',),
 ('ALEMANIA;PAISES BAJOS',),
 ('AMERICA;ASIA',),
 ('AMERICA;ASIA;EUROPA;ARABIA SAUDI;CHILE;COLOMBIA;COSTA RICA;EMIRATOS ARABES UNIDOS;PANAMA;PERU;TURQUIA',),
 ('AMERICA;ASIA;UE',),
 ('AMERICA;EUROPA;UE',),
 ('ANDORRA;CHINA;ECUADOR;EEUU;GHANA;GIBRALTAR;HONG KONG',),
 ('ARABIA SAUDI;BRASIL;FRANCIA;INDIA;ITALIA;PAISES BAJOS;PORTUGAL',),
 ('ARABIA SAUDI;COLOMBIA;MEXICO',),
 ('ARABIA SAUDI;COREA DEL SUR;EEUU;HONG KONG;LITUANIA;PERU;PORTUGAL;RUMANIA;SINGAPUR;VIETNAM',),
 ('ARGELIA;CANADA;MEXICO;MONTENEGRO',),
 ('ARGENTINA',),
 ('ALEMANIA;CANADA;EEUU;FRANCIA;PORTUGAL;UK',),
 ('ALEMANIA;CANADA;CHINA;FRANCIA;GRECIA;ITALIA;PORTUGAL;RUSIA',),
 ('ALEMANIA;BELGICA;PAISES BAJOS',),
 ('AFRICA;ASIA;EUROPA;CENTRO AMERICA;SUDAMERICA',),
 ('AFRICA;AMERICA;ASIA;EUROPA;UE;EEUU',),
 ('AFRICA;AMERICA;ASIA;ORIENTE MEDIO;UE',),
 ('AFRICA;AMERICA;EUROPA',),
 ('AFRICA;AMERICA;EUROPA;ALEMANIA;AUSTRALIA;FRANCIA;GROENLANDIA;ITALIA;NUEVA ZELANDA;POLONIA',),
 ('AFRICA;AMERICA;EUROPA;OCEANIA',),
 ('AFRICA;AMERICA;UE',),
 ('AFRICA;ASIA;CENTRO AMERICA;SUDAMERICA;UE;EEUU',),
 ('AFRICA;ASIA;EUROPA',),
 ('AFRICA;ASIA;EUROPA;CENTRO AMERICA;SUDAMERICA;UE;AUSTRALIA;EEUU',),
 ('ALEMANIA;BELGICA;FRANCIA;ITALIA;REPUBLICA CHECA;SUECIA;SUIZA',),
 ('AFRICA;ASIA;EUROPA;NORTE AMERICA;CENTRO AMERICA;SUDAMERICA;ORIENTE MEDIO;AUSTRALIA;NUEVA ZELANDA',),
 ('AFRICA;CENTRO AMERICA;SUDAMERICA',),
 ('AFRICA;UE',),
 ('ALEMANIA;ANDORRA;ARABIA SAUDI;ARGENTINA;AUSTRALIA;AUSTRIA;BAHREIN;BELGICA;BRASIL;BULGARIA;CANADA;CHILE;COLOMBIA;COREA DEL SUR;COSTA RICA;DINAMARCA;ECUADOR;EGIPTO;EMIRATOS ARABES UNIDOS;ESLOVENIA;EEUU',),
 ('ALEMANIA;ARGENTINA;AUSTRIA;BELGICA;BRASIL;CANADA;CHINA;COREA DEL SUR;ECUADOR;EGIPTO;EEUU;FRANCIA;GRECIA;HONG KONG;ISRAEL;ITALIA;MARRUECOS;PAKISTAN;POLONIA;PORTUGAL;UK;REPUBLICA CHECA;RUMANIA;RUSIA;SUI',),
 ('ALEMANIA;ARGENTINA;AUSTRIA;BELGICA;CHINA;EMIRATOS ARABES UNIDOS;EEUU;FINLANDIA;FRANCIA;INDIA;ITALIA;JAPON;MALASIA;MEXICO;UK;SUECIA;SUIZA',),
 ('ALEMANIA;BELGICA;CANADA;COLOMBIA;EEUU;FINLANDIA;HUNGRIA;IRLANDA;ITALIA;JAPON;MEXICO;PAISES BAJOS;POLONIA;UK;SUECIA',),
 ('ALEMANIA;BELGICA;EEUU;IRLANDA;UK;SUIZA',),
 ('ARGENTINA;BULGARIA;ECUADOR',),
 ('ASIA;EUROPA',),
 ('EMIRATOS ARABES UNIDOS',),
 ('ASIA;EUROPA;AFRICA DEL NORTE;CENTRO AMERICA;SUDAMERICA;BRASIL;UK',),
 ('CHILE;COLOMBIA;PERU',),
 ('CHILE;JAPON;REPUBLICA DOMINICANA;SUIZA',),
 ('CHINA;EEUU;SUIZA',),
 ('CHINA;FRANCIA;RUMANIA;RUSIA',),
 ('CHINA;UE',),
 ('CHINA;UK;EEUU',),
 ('COLOMBIA;EEUU;FRANCIA;POLONIA;PORTUGAL;RUSIA;SUDAFRICA',),
 ('COLOMBIA;MALASIA',),
 ('CUBA;MARRUECOS',),
 ('CUBA;MEXICO',),
 ('CUBA;VENEZUELA',),
 ('DINAMARCA',),
 ('DINAMARCA;FINLANDIA;POLONIA;MEXICO;PANAMA;EEUU;JAPON;CANADA;ALEMANIA;UK',),
 ('AFRICA DEL NORTE;ORIENTE MEDIO;SUDAMERICA;UE',),
 ('EEUU;BRASIL;MEXICO',),
 ('EEUU;MEXICO',),
 ('EEUU;RUSIA',),
 ('EEUU;UE',),
 ('EGIPTO;AMERICA;EUROPA',),
 ('CHILE;COLOMBIA;COREA DEL SUR;EEUU',),
 ('CENTRO AMERICA;SUDAMERICA;UE;MEXICO',),
 ('CENTRO AMERICA;SUDAMERICA;ESCANDINAVIA;UE;MEXICO',),
 ('BELGICA;FRANCIA;SUIZA',),
 ('ASIA;EUROPA;BRASIL;EEUU',),
 ('ASIA;EUROPA;PAISES ARABES',),
 ('ASIA;FINLANDIA',),
 ('AUSTRALIA;EMIRATOS ARABES UNIDOS;MEXICO',),
 ('BELGICA;BRASIL;EEUU;JAPON;PAISES BAJOS;SUIZA',),
 ('BELGICA;EEUU;LUXEMBURGO;PAISES BAJOS;UK',),
 ('BELGICA;FRANCIA;ITALIA;UK',),
 ('BELGICA;FRANCIA;PORTUGAL',),
 ('BELGICA;HUNGRIA;REPUBLICA CHECA;SUIZA',),
 ('CENTRO AMERICA;ARGENTINA;CHILE;COLOMBIA;ECUADOR;MEXICO;PERU',),
 ('BELGICA;MEXICO;PANAMA',),
 ('BELGICA;PORTUGAL;RUMANIA;SUECIA',),
 ('BELGICA;VENEZUELA;UK',),
 ('BRASIL',),
 ('BRASIL;CAMERUN;COSTA DE MARFIL;JAMAICA;MEXICO',),
 ('BRASIL;CHILE;COLOMBIA;COSTA DE MARFIL;CUBA;ECUADOR;MEXICO;PERU;SEYCHELLES',),
 ('BRASIL;PERU;REPUBLICA CHECA;SUIZA;URUGUAY',),
 ('CANADA;COREA DEL SUR;FRANCIA;ITALIA',),
 ('UK;PAISES BAJOS',)]

In [136]:
df_2022_col_comunes =  df_2022_col[df_2022_col['Código NIF'].isin(nif_comunes)]
df_2022_col_comunes.drop_duplicates(inplace=True)
df_2022_col_comunes.reset_index(inplace=True, drop=True)
df_2022_col_comunes.head()

C:\Users\josu1\AppData\Local\Temp\ipykernel_4112\981536150.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022_col_comunes.drop_duplicates(inplace=True)

,Nombre,Código NIF,Localidad,Provincia,País,Código primario CNAE 2009,Literal código CNAE 2009 primario,Fecha constitución,Importador / Exportador,Países importación,Países exportación,Resultado del Ejercicio\nmil EUR\n2022,Total activo\nmil EUR\n2022,Ingresos de explotación\nmil EUR\n2022,Activo circulante\nmil EUR\n2022,Pasivo líquido\nmil EUR\n2022,Resultado Explotación\nmil EUR\n2022,Otros activos líquidos\nmil EUR\n2022,Capital suscrito\nmil EUR\n2022,Otros fondos propios\nmil EUR\n2022
0,IBERDROLA CLIENTES SOCIEDAD ANONIMA.,A95758389,BILBAO,Vizcaya,ESPANA,3514,Comercio de energía eléctrica,2014-03-17 00:00:00,Exportador,NaN,UE,627609,3252348,14505887,2768672,1678552,808712,439508,155295,1344809
1,PAN AMERICAN ENERGY SL.,B88260203,BILBAO,Vizcaya,ESPANA,6420,Actividades de las sociedades holding,1997-09-29 00:00:00,Exportador,NaN,ARGENTINA,477940,14448655,5112628,1700432,1727270,578995,742038,2093033,5777889
2,IBERDROLA ENERGIA ESPAÑA SOCIEDAD ANONIMA.,A95758371,BILBAO,Vizcaya,ESPANA,4611,Intermediarios del comercio de materias primas...,2014-03-17 00:00:00,Exportador,NaN,UE,923275,7184141,5004915,3882794,2219290,1564280,2676848,1985452,-772285
3,ALVEAN SUGAR SOCIEDAD LIMITADA.,B95773057,BILBAO,Vizcaya,ESPANA,4636,"Comercio al por mayor de azúcar, chocolate y c...",2014-07-17 00:00:00,Importador / Exportador,NaN,NaN,67407,835248,3994744,799119,487710,84885,352001,30857,312183
4,"IBERDROLA, SOCIEDAD ANONIMA",A48010615,BILBAO,Vizcaya,ESPANA,6420,Actividades de las sociedades holding,1901-07-19 00:00:00,Exportador,NaN,UE,2840000,53343000,3058000,3301000,10228000,3167000,3003000,4772000,26909000

In [137]:
df_2020_comunes =  df_2020[df_2020['Código NIF'].isin(nif_comunes)]
df_2020_comunes.drop_duplicates(inplace=True)
df_2020_comunes.reset_index(inplace=True, drop=True)
df_2020_comunes.head()

C:\Users\josu1\AppData\Local\Temp\ipykernel_4112\3413841440.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020_comunes.drop_duplicates(inplace=True)

,Unnamed: 0.1,Unnamed: 0,Nombre,Código NIF,Localidad,Provincia,País,Código primario CNAE 2009,Literal código CNAE 2009 primario,Fecha constitución,...,Resultado Actividades Ordinarias\nmil EUR\n2020,Ingresos extraordinarios\nmil EUR\n2020,Gastos extraordinarios\nmil EUR\n2020,Resultados actividades extraordinarias\nmil EUR\n2020,Resultado del Ejercicio\nmil EUR\n2020,Materiales\nmil EUR\n2020,Gastos de personal\nmil EUR\n2020,Dotaciones para amortiz. de inmovil.\nmil EUR\n2020,Otros Conceptos de Explotación\nmil EUR\n2020,Gastos financieros y gastos asimilados\nmil EUR\n2020
0,0,1,PETROLEOS DEL NORTE SOCIEDAD ANONIMA,A48053243,MUSKIZ,Vizcaya,ESPANA,1920,Refino de petróleo,1968-01-01 00:00:00,...,-140086,n.d.,n.d.,n.d.,-140086,3362167,93672,97175,-225893,2613
1,1,2,SIDENOR ACEROS ESPECIALES SLU,B01292903,BASAURI,Vizcaya,ESPANA,2410,"Fabricación de productos básicos de hierro, ac...",1999-11-18 00:00:00,...,-39853,n.d.,n.d.,n.d.,-39853,244284,90310,22212,-136437,3684
2,2,3,BRIDGESTONE HISPANIA MANUFACTURING SOCIEDAD LI...,B95922688,BASAURI,Vizcaya,ESPANA,2211,Fabricación de neumáticos y cámaras de caucho;...,2018-05-31 00:00:00,...,1792,n.d.,n.d.,n.d.,1792,282346,153205,43388,-76136,548
3,3,4,COMPAÑIA NORTEÑA DE BEBIDAS GASEOSAS NORBEGA S...,B48023030,GALDAKAO,Vizcaya,ESPANA,1107,Fabricación de bebidas no alcohólicas; producc...,1955-07-06 00:00:00,...,18209.709,n.d.,n.d.,n.d.,18209.709,608261.681,19561.039,14293.748,-61482.757,n.d.
4,4,5,BAHIA DE BIZKAIA ELECTRICIDAD SOCIEDAD LIMITADA,B48969877,ZIERBENA,Vizcaya,ESPANA,3519,Producción de energía eléctrica de otros tipos,1998-04-30 00:00:00,...,1146.572,n.d.,n.d.,n.d.,1146.572,132891.325,3818.954,23742.362,-15559.192,64.766

In [138]:
df_2022_comunes =  df_2022[df_2022['Código NIF'].isin(nif_comunes)]
df_2022_comunes.reset_index(inplace=True, drop=True)
df_2022_comunes.drop_duplicates(inplace=True)
df_2022_comunes.reset_index(inplace=True, drop=True)
df_2022_comunes.head()

C:\Users\josu1\AppData\Local\Temp\ipykernel_4112\491666476.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022_comunes.drop_duplicates(inplace=True)

,Unnamed: 0.1,Unnamed: 0,Nombre,Código NIF,Localidad,Provincia,País,Código primario CNAE 2009,Literal código CNAE 2009 primario,Fecha constitución,...,Resultado Actividades Ordinarias\nmil EUR\n2022,Ingresos extraordinarios\nmil EUR\n2022,Gastos extraordinarios\nmil EUR\n2022,Resultados actividades extraordinarias\nmil EUR\n2022,Resultado del Ejercicio\nmil EUR\n2022,Materiales\nmil EUR\n2022,Gastos de personal\nmil EUR\n2022,Dotaciones para amortiz. de inmovil.\nmil EUR\n2022,Otros Conceptos de Explotación\nmil EUR\n2022,Gastos financieros y gastos asimilados\nmil EUR\n2022
0,0,1.0,IBERDROLA CLIENTES SOCIEDAD ANONIMA.,A95758389,BILBAO,Vizcaya,ESPANA,3514,Comercio de energía eléctrica,2014-03-17 00:00:00,...,627609,n.d.,n.d.,n.d.,627609,12868251,77500,9612,-741812,1502
1,1,2.0,PAN AMERICAN ENERGY SL.,B88260203,BILBAO,Vizcaya,ESPANA,6420,Actividades de las sociedades holding,1997-09-29 00:00:00,...,477940,n.d.,n.d.,n.d.,477940,1134150,489580,805893,-2104010,488731
2,2,3.0,IBERDROLA ENERGIA ESPAÑA SOCIEDAD ANONIMA.,A95758371,BILBAO,Vizcaya,ESPANA,4611,Intermediarios del comercio de materias primas...,2014-03-17 00:00:00,...,923275,n.d.,n.d.,n.d.,923275,4046923,26987,2654,635929,9620
3,3,4.0,ALVEAN SUGAR SOCIEDAD LIMITADA.,B95773057,BILBAO,Vizcaya,ESPANA,4636,"Comercio al por mayor de azúcar, chocolate y c...",2014-07-17 00:00:00,...,67407,n.d.,n.d.,n.d.,67407,3874052,20475,1945,-13387,12819
4,4,5.0,"IBERDROLA, SOCIEDAD ANONIMA",A48010615,BILBAO,Vizcaya,ESPANA,6420,Actividades de las sociedades holding,1901-07-19 00:00:00,...,2840000,n.d.,n.d.,n.d.,2840000,n.d.,166000,72000,347000,322000

In [139]:
df_2022_col_comunes.columns

Index(['Nombre', 'Código NIF', 'Localidad', 'Provincia', 'País',
       'Código primario CNAE 2009', 'Literal código CNAE 2009 primario',
       'Fecha constitución', 'Importador / Exportador', 'Países importación',
       'Países exportación', 'Resultado del Ejercicio\nmil EUR\n2022',
       'Total activo\nmil EUR\n2022', 'Ingresos de explotación\nmil EUR\n2022',
       'Activo circulante\nmil EUR\n2022', 'Pasivo líquido\nmil EUR\n2022',
       'Resultado Explotación\nmil EUR\n2022',
       'Otros activos líquidos\nmil EUR\n2022',
       'Capital suscrito\nmil EUR\n2022',
       'Otros fondos propios\nmil EUR\n2022'],
      dtype='object')

In [140]:
df_2020_comunes.replace('n.d.',np.nan,inplace=True)
df_2022_comunes.replace('n.d.',np.nan,inplace=True)
df_2022_col_comunes.replace('n.d.',np.nan,inplace=True)

C:\Users\josu1\AppData\Local\Temp\ipykernel_4112\3976597485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2020_comunes.replace('n.d.',np.nan,inplace=True)
C:\Users\josu1\AppData\Local\Temp\ipykernel_4112\3976597485.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022_comunes.replace('n.d.',np.nan,inplace=True)
C:\Users\josu1\AppData\Local\Temp\ipykernel_4112\3976597485.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022_col_comunes.replace('n.d.',np.nan,inplace=True)

In [141]:
print(df_2022_col_comunes.isna().sum())

Nombre                                        0
Código NIF                                    0
Localidad                                     1
Provincia                                     0
País                                          0
Código primario CNAE 2009                     0
Literal código CNAE 2009 primario             0
Fecha constitución                           14
Importador / Exportador                       0
Países importación                        37019
Países exportación                        38496
Resultado del Ejercicio\nmil EUR\n2022    10253
Total activo\nmil EUR\n2022               10106
Ingresos de explotación\nmil EUR\n2022    11011
Activo circulante\nmil EUR\n2022          10121
Pasivo líquido\nmil EUR\n2022             10341
Resultado Explotación\nmil EUR\n2022      10217
Otros activos líquidos\nmil EUR\n2022     10509
Capital suscrito\nmil EUR\n2022           10107
Otros fondos propios\nmil EUR\n2022       10134
dtype: int64

In [148]:
df_2022_col_comunes=df_2022_col_comunes[df_2022_col_comunes['Total activo\nmil EUR\n2022'].notna()]
df_2022_col_comunes.isna().sum()

Nombre                                        0
Código NIF                                    0
Localidad                                     0
Provincia                                     0
País                                          0
Código primario CNAE 2009                     0
Literal código CNAE 2009 primario             0
Fecha constitución                            5
Importador / Exportador                       0
Países importación                        27301
Países exportación                        28557
Resultado del Ejercicio\nmil EUR\n2022      147
Total activo\nmil EUR\n2022                   0
Ingresos de explotación\nmil EUR\n2022      905
Activo circulante\nmil EUR\n2022             15
Pasivo líquido\nmil EUR\n2022               235
Resultado Explotación\nmil EUR\n2022        111
Otros activos líquidos\nmil EUR\n2022       403
Capital suscrito\nmil EUR\n2022               1
Otros fondos propios\nmil EUR\n2022          28
dtype: int64

In [164]:
df_2020_2022=df_2022_col_comunes.merge(df_2020_ingexp, on='Código NIF', how='left')
df_2020_2022.to_excel('df_2020_2022.xlsx' )

In [ ]:
# ETXEKOLANA
df_2020_2022['Ingresos de explotación\nmil EUR\n2020'].apply(lambda x: df_2020_2022['Ingresos de explotación\nmil EUR\n2022'] if x == np.nan else x )

In [162]:
print(len(df_2022))
print(len(df_2020_2022))
df_2020_2022.isna().sum()

39479
29358

Nombre                                        0
Código NIF                                    0
Localidad                                     0
Provincia                                     0
País                                          0
Código primario CNAE 2009                     0
Literal código CNAE 2009 primario             0
Fecha constitución                            5
Importador / Exportador                       0
Países importación                        27301
Países exportación                        28557
Resultado del Ejercicio\nmil EUR\n2022      147
Total activo\nmil EUR\n2022                   0
Ingresos de explotación\nmil EUR\n2022      905
Activo circulante\nmil EUR\n2022             15
Pasivo líquido\nmil EUR\n2022               235
Resultado Explotación\nmil EUR\n2022        111
Otros activos líquidos\nmil EUR\n2022       403
Capital suscrito\nmil EUR\n2022               1
Otros fondos propios\nmil EUR\n2022          28
Ingresos de explotación\nmil EUR\n2020     3378
dtype: int64

In [113]:
print(df_2022_comunes.isna().sum())

Unnamed: 0.1                                                 0
Unnamed: 0                                               19349
Nombre                                                       0
Código NIF                                                   0
Localidad                                                    1
Provincia                                                    0
País                                                         0
Código primario CNAE 2009                                    0
Literal código CNAE 2009 primario                            0
Fecha constitución                                          14
Importador / Exportador                                      0
Países importación                                       37019
Países exportación                                       38496
Otros activos líquidos\nmil EUR\n2022                    10509
Inmovilizado\nmil EUR\n2022                              11886
Inmovilizado inmaterial\nmil EUR\n2022                   31019
Inmovilizado material\nmil EUR\n2022                     15112
Otros activos fijos\nmil EUR\n2022                       18680
Activo circulante\nmil EUR\n2022                         10121
Existencias\nmil EUR\n2022                               23953
Deudores\nmil EUR\n2022                                  12431
Tesorería\nmil EUR\n2022                                 11037
Total activo\nmil EUR\n2022                              10106
Capital suscrito\nmil EUR\n2022                          10107
Otros fondos propios\nmil EUR\n2022                      10134
Pasivo fijo\nmil EUR\n2022                               20951
Acreedores a L. P.\nmil EUR\n2022                        22311
Otros pasivos fijos\nmil EUR\n2022                       10106
Pasivo líquido\nmil EUR\n2022                            10341
Deudas financieras\nmil EUR\n2022                        29308
Acreedores comerciales\nmil EUR\n2022                    18657
Otros pasivos líquidos\nmil EUR\n2022                    10573
Total pasivo y capital propio\nmil EUR\n2022             10106
Número empleados\nÚlt. año disp.                          9737
Número empleados\n2022                                   16283
Ingresos de explotación\nmil EUR\n2022                   11011
Importe neto Cifra de Ventas\nmil EUR\n2022              12703
Consumo de mercaderías y de materias\nmil EUR\n2022      17165
Resultado bruto\nmil EUR\n2022                           10828
Otros gastos de explotación\nmil EUR\n2022               10202
Resultado Explotación\nmil EUR\n2022                     10217
Ingresos financieros\nmil EUR\n2022                      10106
Gastos financieros\nmil EUR\n2022                        10106
Resultado financiero\nmil EUR\n2022                      10106
Result. ordinarios antes Impuestos\nmil EUR\n2022        10261
Impuestos sobre sociedades\nmil EUR\n2022                16109
Resultado Actividades Ordinarias\nmil EUR\n2022          10253
Ingresos extraordinarios\nmil EUR\n2022                  39464
Gastos extraordinarios\nmil EUR\n2022                    39464
Resultados actividades extraordinarias\nmil EUR\n2022    39448
Resultado del Ejercicio\nmil EUR\n2022                   10253
Materiales\nmil EUR\n2022                                17323
Gastos de personal\nmil EUR\n2022                        14554
Dotaciones para amortiz. de inmovil.\nmil EUR\n2022      15840
Otros Conceptos de Explotación\nmil EUR\n2022            10229
Gastos financieros y gastos asimilados\nmil EUR\n2022    17904
dtype: int64

In [114]:
df_2020_comunes[df_2020_comunes['Total activo\nmil EUR\n2020'].notna()].isna().sum()

Unnamed: 0.1                                                 0
Unnamed: 0                                                   0
Nombre                                                       0
Código NIF                                                   0
Localidad                                                    1
Provincia                                                    0
País                                                         0
Código primario CNAE 2009                                    0
Literal código CNAE 2009 primario                            0
Fecha constitución                                           8
Importador / Exportador                                      0
Países importación                                       30705
Países exportación                                       32124
Otros activos líquidos\nmil EUR\n2020                      477
Inmovilizado\nmil EUR\n2020                               2243
Inmovilizado inmaterial\nmil EUR\n2020                   24255
Inmovilizado material\nmil EUR\n2020                      5771
Otros activos fijos\nmil EUR\n2020                       10360
Activo circulante\nmil EUR\n2020                            34
Existencias\nmil EUR\n2020                               15445
Deudores\nmil EUR\n2020                                   2404
Tesorería\nmil EUR\n2020                                  1070
Total activo\nmil EUR\n2020                                  0
Capital suscrito\nmil EUR\n2020                              1
Otros fondos propios\nmil EUR\n2020                         98
Pasivo fijo\nmil EUR\n2020                               11707
Acreedores a L. P.\nmil EUR\n2020                        13143
Otros pasivos fijos\nmil EUR\n2020                           0
Pasivo líquido\nmil EUR\n2020                              319
Deudas financieras\nmil EUR\n2020                        22140
Acreedores comerciales\nmil EUR\n2020                     9677
Otros pasivos líquidos\nmil EUR\n2020                      580
Total pasivo y capital propio\nmil EUR\n2020                 0
Número empleados\n2020                                    7138
Ingresos de explotación\nmil EUR\n2020                    1167
Importe neto Cifra de Ventas\nmil EUR\n2020               2986
Consumo de mercaderías y de materias\nmil EUR\n2020       7895
Resultado bruto\nmil EUR\n2020                             902
Otros gastos de explotación\nmil EUR\n2020                 174
Resultado Explotación\nmil EUR\n2020                       213
Ingresos financieros\nmil EUR\n2020                          0
Gastos financieros\nmil EUR\n2020                            0
Resultado financiero\nmil EUR\n2020                          0
Result. ordinarios antes Impuestos\nmil EUR\n2020          286
Impuestos sobre sociedades\nmil EUR\n2020                 8198
Resultado Actividades Ordinarias\nmil EUR\n2020            279
Ingresos extraordinarios\nmil EUR\n2020                  33061
Gastos extraordinarios\nmil EUR\n2020                    33061
Resultados actividades extraordinarias\nmil EUR\n2020    33043
Resultado del Ejercicio\nmil EUR\n2020                     279
Materiales\nmil EUR\n2020                                 8113
Gastos de personal\nmil EUR\n2020                         5144
Dotaciones para amortiz. de inmovil.\nmil EUR\n2020       6790
Otros Conceptos de Explotación\nmil EUR\n2020              216
Gastos financieros y gastos asimilados\nmil EUR\n2020     8306
dtype: int64

- ver cuales son las variables que nos interesan y cuales no para eliminarlas, correlacion haciendo dropna?
- ver las filas que tienen casi todo na por si eliminamos las filas y nos quedamos con las variables
- interpolacion en alguna de las columnas?
- pensar que nuevas varibales nos pueden valer.
-pensar los modelos que vamos a utilizar para el clustering, k-means, clustering jerarquico...
- organizar los 4 puntos del trabajo(4 archivos diferentes para cada paso):
1. Iniciar el proyecto requiere primero comprender el significado de las
variables presentes en las bases de datos y realizar una depuración de
estos datos para que sean aptos para trabajar con ellos.

2. Seguidamente, se procederá al cálculo de los ratios financieros.

3. Luego, basándose en los cálculos anteriores, se segmentarán las
empresas mediante el uso de algoritmos de clustering.

4. Tras segmentar las empresas en diferentes grupos, estos se deberán
analizar individualmente para poder seleccionar los productos financieros
que mejor se adecuan a cada tipo de empresa. Se realizará una
investigación y análisis detallado de una amplia gama de productos
financieros disponibles en el mercado. Esto incluirá, pero no se limitará a,
préstamos, líneas de crédito, opciones de inversión, y seguros
empresariales. Esta investigación deberá utilizar como punto de partida al
cliente principal, Inetum, y valorar sus posibilidades a la hora de elegir los
productos financieros.


ESTA ES LA DISTRIBUCIÓN QUE SE PROPONE:
1. Procesamiento
2. Análisis exploratorio
3. Selección del modelo
4. Optimización del modelo
5. Resultados (visualización)

- Cada cosa en un cuaderno diferente
- De cada cuaderno sale un nuevo fichero de datos
- El nuevo fichero de datos se utilizará en el siguiente cuaderno
- Es un proceso secuencial